<!DOCTYPE html>
<html>
<head>
<title>Music Blog</title>
</head>
<body>

<h1>Music Blog</h1>
<p>A music genre is a conventional category that identifies some pieces of music as belonging to a shared tradition or set of conventions. Music can be divided into different genres in many different ways. The artistic nature of music means that these classifications are often subjective and controversial, and some genres may overlap.</p>
<br>
<p>Electronic Dance Music:
Generally referred as EDM, this form of music is produced by DJs who add dozens of tones to a piece to create unique music. You can hear them in clubs or even live, depending upon your accessibility for the same. In the early twenties, electronic dance music was known in the form of Jamaican dub music, the electronic music of Kraftwerk, the disco music of Giorgio Moroder, the Yellow Magic Orchestra and many more.</p>
<br>
<p>Rock Music:
Originated as “Rock & Roll” in the United States, Rock music has been rocking the world since the 1950s. It is a form of music that started actually around string instruments, but now uses other modern instruments too making it a little difficult to give it an accurate definition. Its loud and strong beats make it popular among the youths. Some of the rock stars who have popularized the culture include Little Richard, Bill Haley and Chuck Berry while rock bands like Pink Floyd, The Doors, Metallica, Nirvana and Megadeth are the modern bands who have taken the culture by storm</p>
<br>
<p>Jazz:
Identified with swing and blue notes, Jazz has its roots both in the West African and European culture. It is said that Jazz is “One of America’s original art forms” and boasts a unique combination of creativity, coactions and interactivity. Originating in the late 19th to early 20th century, Jazz has also played an important role in introducing the world to a number of women performers like Ella Fitzgerald, Betty Carter, Abbey Lincoln and Ethel Waters.</p>
<br>
<p>Dubstep:
The use of instruments attracting music lovers for its bass and rhythm, this falls in the electronic music genre. People consider it to be a darker form of music, but since its birth in the late 1990s, this genre has successfully made its place in the industry.</p>
<br>
<p>Rhythm and Blues:
Vocalists like Rihanna, Mariah Carey, Beyoncé, Usher and the legendary Michael Jackson have all made it huge in the music industry with their love for this form of music. Originated in the 1940s, this African-American music is a combination of hip hop, funk, dance, pop and soul focusing on themes like relationships, sex and freedom.</p>
<br>
<p>Techno:
You may have listened to a number of techno music while clubbing, but it is Detroit techno that is considered to be the foundation of this form of music. Unlike the days of its emergence, the use of technology today has greatly enhanced the quality of techno style music and popularizing it among people day by day.</p>
<br>
<p>Country Music:
Another popular genre of American music which originated in the 1920s, Country music has its roots from American folk and western music. It is formed using simple forms of instruments ranging from electric and steel guitars to drums and mandolin or mouth organ. Some very popular country music singers include Shania Twain, Johnny Cash Taylor Swift and Kenny Rogers.</p>
<br>
<p>Electro:
A perfect blend of hip hop and electronic music, electro or electro-funk uses drum machine, vocoder and talkbox helping it to distinguish itself from another similar form of music, Disco. Notable artists who have been into this form of music include Arthur Baker, Freeez, Man Parrish and Midnight Star.</p>
<br>
<p>Indie Rock:
Falling in the genre of alternative rock music, Indie Rock originated in the 1980s and has gradually changed the music industry. After a decade, it also gave birth to a couple of sun-genres in related styles such as math rock, emo, noise pop, post rock and lo-fi.</p>
<br>
<p>Pop Music:
“Pop” is a term derived from “Popular” and thus Pop Music is known to be a genre of popular music. With its roots in the rock & roll style, this form can include any form of music ranging from urban and dance to rock, country and Latin. Instruments highly used are electric guitars, synthesizer drums as well as bass and one can listen to this form of music by listening to songs by Britney Spears, Madonna, Beyonce Lady Gaga and of course the “King of Pop”, Michael Jackson.
</p>

</body>
</html># This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
